rpc_url: https://eth.llamarpc.com
chains:
  - name: arena-z
    display_name: Arena-Z
    opstack:
      optimism_portal_address: 0xB20f99b598E8d888d1887715439851BC68806b22
  - name: base
    display_name: Base
    opstack:
      optimism_portal_address: 0x49048044D57e1C92A77f79988d21Fa8fAF74E97e
  - name: bob
    display_name: BOB
    opstack:
      optimism_portal_address: 0x8AdeE124447435fE03e3CD24dF3f4cAE32E65a3E
  - name: boba-mainnet
    display_name: Boba Mainnet
    opstack:
      optimism_portal_address: 0x7B02D13904D8e6E0f0Efaf756aB14Cb0FF21eE7e
  - name: ethernity
    display_name: Ethernity
    opstack:
      optimism_portal_address: 0xDA29f0B4da6c23f6c1aF273945c290C0268c4ea9
  - name: hashkey-chain
    display_name: HashKey Chain
    opstack:
      optimism_portal_address: 0xe7Aa79B59CAc06F9706D896a047fEb9d3BDA8bD3
  - name: ink
    display_name: Ink
    opstack:
      optimism_portal_address: 0x5d66C1782664115999C47c9fA5cd031f495D3e4F
  - name: lisk
    display_name: Lisk
    opstack:
      optimism_portal_address: 0x26dB93F8b8b4f7016240af62F7730979d353f9A7
  - name: metal-l2
    display_name: Metal L2
    opstack:
      optimism_portal_address: 0x3F37aBdE2C6b5B2ed6F8045787Df1ED1E3753956
  - name: mint-mainnet
    display_name: Mint Mainnet
    opstack:
      optimism_portal_address: 0x59625d1FE0Eeb8114a4d13c863978F39b3471781
  - name: mode
    display_name: Mode
    opstack:
      optimism_portal_address: 0x8B34b14c7c7123459Cf3076b8Cb929BE097d0C07
  - name: op-mainnet
    display_name: OP Mainnet
    opstack:
      optimism_portal_address: 0xbEb5Fc579115071764c7423A4f12eDde41f106Ed
  - name: polynomial
    display_name: Polynomial
    opstack:
      optimism_portal_address: 0x034cbb620d1e0e4C2E29845229bEAc57083b04eC
  - name: race-mainnet
    display_name: RACE Mainnet
    opstack:
      optimism_portal_address: 0x0485Ca8A73682B3D3f5ae98cdca1E5b512E728e9
  - name: settlus-mainnet
    display_name: Settlus Mainnet
    opstack:
      optimism_portal_address: 0xFc1D560eB01443e31B0EB56620703E80e42A7E4e
  - name: shape
    display_name: Shape
    opstack:
      optimism_portal_address: 0xEB06fFa16011B5628BaB98E29776361c83741dd3
  - name: snaxchain
    display_name: SnaxChain
    opstack:
      optimism_portal_address: 0x936D881b4760D5e9b6D55b774f65c509236b4743
  - name: soneium
    display_name: Soneium
    opstack:
      optimism_portal_address: 0x88e529A6ccd302c948689Cd5156C83D4614FAE92
  - name: superseed
    display_name: Superseed
    opstack:
      optimism_portal_address: 0x2c2150aa5c75A24fB93d4fD2F2a895D618054f07
  - name: swan-chain-mainnet
    display_name: Swan Chain Mainnet
    opstack:
      optimism_portal_address: 0xBa50434BC5fCC07406b1baD9AC72a4CDf776db15
  - name: swellchain
    display_name: Swellchain
    opstack:
      optimism_portal_address: 0x758E0EE66102816F5C3Ec9ECc1188860fbb87812
  - name: binary-mainnet
    display_name: Binary Mainnet
    opstack:
      optimism_portal_address: 0x5ff88fcF8e9947f45F4cAf8FFd5231B5DdF05e0A
  - name: unichain
    display_name: Unichain
    opstack:
      optimism_portal_address: 0x0bd48f6B86a26D3a217d0Fa6FfE2B491B956A7a2
  - name: world-chain
    display_name: World Chain
    opstack:
      optimism_portal_address: 0xd5ec14a83B7d95BE1E2Ac12523e2dEE12Cbeea6C
  - name: zora
    display_name: Zora
    opstack:
      optimism_portal_address: 0x1a0ad011913A150f69f6A19DF447A0CfD9551054
  - name: "arbitrum"
    display_name: "Arbitrum One"
    arbitrum:
      rpc_url: "https://arb1.arbitrum.io/rpc"
      delayed_inbox_address: "0x4Dbd4fc535Ac27206064B68FfCf827b0A60BAB3f"
  - name: "arbitrum"
    display_name: "Arbitrum Nova"
    arbitrum:
      rpc_url: "https://nova.arbitrum.io/rpc"
      delayed_inbox_address: "0xc4448b71118c9071Bcb9734A0EAc55D18A153949"
