chains:
  - name: "op-mainnet"
    display_name: "OP Mainnet"
    rpc_url: "https://mainnet.optimism.io"
    opstack:
      optimism_portal_address: "0xbEb5Fc579115071764c7423A4f12eDde41f106Ed"
  - name: "base"
    display_name: "Base"
    rpc_url: "https://mainnet.base.org"
    opstack:
      optimism_portal_address: "0x49048044D57e1C92A77f79988d21Fa8fAF74E97e"
  - name: "soneium"
    display_name: "Soneium"
    rpc_url: "https://rpc.soneium.org"
    opstack:
      optimism_portal_address: "0x88e529A6ccd302c948689Cd5156C83D4614FAE92"
  - name: "unichain"
    display_name: "Unichain"
    rpc_url: "https://rpc.unichain.org"
    opstack:
      optimism_portal_address: "0x0bd48f6B86a26D3a217d0Fa6FfE2B491B956A7a2"
  - name: "ink"
    display_name: "Ink"
    rpc_url: "https://rpc-gel.inkonchain.com"
    opstack:
      optimism_portal_address: "0x5d66C1782664115999C47c9fA5cd031f495D3e4F"
  - name: "arbitrum-sepolia"
    display_name: "Arbitrum Sepolia (Disabled)"
    type: "arbitrum"
    rpc_url: "https://api.zan.top/arb-sepolia"
    arbitrum:
      delayed_inbox_address: "0x4200000000000000000000000000000000000015"
