rpc_url: "https://eth.llamarpc.com"
chains:
  - name: "op-mainnet"
    display_name: "OP Mainnet"
    opstack:
      optimism_portal_address: "0xbEb5Fc579115071764c7423A4f12eDde41f106Ed"
  - name: "base"
    display_name: "Base"
    opstack:
      optimism_portal_address: "0x49048044D57e1C92A77f79988d21Fa8fAF74E97e"
  - name: "soneium"
    display_name: "Soneium"
    opstack:
      optimism_portal_address: "0x88e529A6ccd302c948689Cd5156C83D4614FAE92"
  - name: "unichain"
    display_name: "Unichain"
    opstack:
      optimism_portal_address: "0x0bd48f6B86a26D3a217d0Fa6FfE2B491B956A7a2"
  - name: "ink"
    display_name: "Ink"
    opstack:
      optimism_portal_address: "0x5d66C1782664115999C47c9fA5cd031f495D3e4F"
  # - name: "arbitrum-sepolia"
  #   display_name: "Arbitrum Sepolia"
  #   type: "arbitrum"
  #   arbitrum:
  #     delayed_inbox_address: "0x4200000000000000000000000000000000000015"
