name: Docker Build & Push
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} -t ghcr.io/${{ github.repository }}:latest .
      - name: Push Docker image (sha)
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: Push Docker image (latest)
        run: |
          docker push ghcr.io/${{ github.repository }}:latest
